[package]
name = "gridded_automata"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26"
wgpu = "0.13"
bytemuck = { version = "1.4", features = [ "derive" ] }
cgmath = "0.18"
pollster = "0.2"
image = "0.24.5"

rand = "*"

[[bin]]
name = "cgol"
path = "src/impl/cgol.rs"

[[bin]]
name = "wire_world"
path = "src/impl/wire_world.rs"

[lib]
name = "gridded_automata"
path = "src/lib/mod.rs"