= Gridded Automata

This is a library for rendering discrete cellular automata using compute shaders. 
Users provide a state function (written in _WGSL_) that returns a cell's new state based on its current state and that of its neighbors. The simulation speed, the way cells are colored, and the type of neighborhood can be tweaked through config options.

Automata cell data can be read from `PGM` image files, which can be in ASCII or binary format (`P2` & `P5` as described https://en.wikipedia.org/wiki/Netpbm[here]). Data can also be read from any other type of image if the library's `from_image` feature is enabled. Note that colors are assigned values in the order they are encountered. For this reason, it's best to provide a "color legend" in the image's topmost row, from left-to-right.

== Examples

A number of classic automata are included as binaries, intended to showcase the library. 

.Binaries
[horizontal]
`cgol` :: Conway's Game of Life
`ww` :: https://mathworld.wolfram.com/WireWorld.html[Wire World] (loads cells from a `PGM` file)
`lant` :: Langton's Ant
`bb` :: https://conwaylife.com/wiki/OCA:Brian's_Brain[Brian's Brain]
`seeds` :: Seeds